version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: dsp-api
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/dsp
      - DRAGONFLYDB_URI=redis://dragonfly:6379
    restart: unless-stopped
    networks:
      - databases
      - web-proxy

networks:
  databases:
    external: true
  web-proxy:
    external: true
